info:
  name: Update Thread
  type: http
  seq: 8

http:
  method: PATCH
  url: "{{baseUrl}}/threads/:id"
  params:
    - name: id
      value: ddfd8765-4910-410b-9e52-997a71b1c1c7
      type: path
  body:
    type: json
    data: |-
      {    "title": "sixth thread",
          "body": "sixth wonderful body",
          "author": "sixth author"
          }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
